# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qi63l2Ub8YHFr_Dx43ieRQRla6HvwKqM
"""

!pip install transformers datasets accelerate scikit-learn pandas torch -q

import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)

df = pd.read_csv("Symptom2Disease.csv")

df.head(5)

df = df.dropna()

df["text"] = df["text"].astype(str)

df["text"] = df["text"].str.lower()

label_encoder = LabelEncoder()

df["label_encoded"] = label_encoder.fit_transform(df["label"])

num_labels = len(label_encoder.classes_)

print("Number of diseases:", num_labels)

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["text"],
    df["label_encoded"],
    test_size=0.1,
    random_state=42,
    stratify=df["label_encoded"]
)

tokenizer = AutoTokenizer.from_pretrained(
    "dmis-lab/biobert-base-cased-v1.1"
)

train_encodings = tokenizer(
    list(train_texts),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    list(val_texts),
    truncation=True,
    padding=True,
    max_length=128
)

class MedicalDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels.iloc[idx])
        return item

    def __len__(self):
        return len(self.labels)


train_dataset = MedicalDataset(train_encodings, train_labels)
val_dataset = MedicalDataset(val_encodings, val_labels)

model = AutoModelForSequenceClassification.from_pretrained(
    "dmis-lab/biobert-base-cased-v1.1",
    num_labels=num_labels
)

training_args = TrainingArguments(

    output_dir="./medical_model",

    learning_rate=2e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=16,

    num_train_epochs=6,

    weight_decay=0.01,

    eval_strategy="epoch", # Changed from evaluation_strategy

    save_strategy="epoch",

    load_best_model_at_end=True,

    logging_dir="./logs",

    fp16=True
)

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    preds = np.argmax(logits, axis=1)

    accuracy = accuracy_score(labels, preds)

    f1 = f1_score(labels, preds, average="weighted")

    return {
        "accuracy": accuracy,
        "f1": f1
    }

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=val_dataset,

    compute_metrics=compute_metrics,

    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()

trainer.evaluate()

model.save_pretrained("medical_diagnosis_transformer")

tokenizer.save_pretrained("medical_diagnosis_transformer")

from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="medical_diagnosis_transformer",
    tokenizer="medical_diagnosis_transformer"
)

prediction = classifier(
    "fever chills sweating headache fatigue vomiting"
)

print(prediction)

pred_label = int(prediction[0]["label"].split("_")[1])

disease = label_encoder.inverse_transform([pred_label])

print("Predicted disease:", disease)

